### ISSUE TITLE
MD: Internal ref link are not rendered

### ISSUE THREAD

**Issue by lmazuel** [theacodes/cmarkgfm#20]
Hello!

For example with this package:
https://pypi.org/project/azure-identity

There is a few link to anchors in that file, for example of MD:
```
Credentials can be chained together and tried in turn until one succeeds; see
[chaining credentials](#chaining-credentials) for details.
```

It works fine in Github, see this link:
https://github.com/Azure/azure-sdk-for-python/blob/master/sdk/identity/azure-identity/README.md#chaining-credentials

It works as well with Sphinx, they generate a div with the right id for that:
![image](https://user-images.githubusercontent.com/1050156/67726765-2d365900-f9a4-11e9-9786-891548b24f3d.png)

PyPI on the other end, does not generate any id:
![image](https://user-images.githubusercontent.com/1050156/67726780-3de6cf00-f9a4-11e9-8a8a-6d8968aab9e1.png)

I was wondering your thoughts about this? If first of all that's something you would want to eventually support, and if yes what strategy you would apply to achieve it. I can't a PR, but at least will be interested to know your feelings about this :)

Thank you for your work!!!

**Comment by lmazuel** [comment]
I realize reading more precisely that you wrap a native library, aplogize for the waste of time here. Do you think it worth searching/opening an issue for this in https://github.com/github/cmark-gfm/issues ?
I wasn't  able to find an issue about this.
Thank you for your time!

**Comment by simonw** [comment]
It looks like `cmark-gfm` does have an issue for this now: https://github.com/github/cmark-gfm/issues/186

**Comment by theacodes** [comment]
Closing this for now, as we can't do anything until upstream fixes it.
