### ISSUE TITLE
Wheel Build Automation

### ISSUE THREAD

**Issue by mbarkhau** [theacodes/cmarkgfm#22]
If it's not too much trouble, could you build and upload wheels for Python 3.8 to pypi. For now I guess I'll have to add gcc to my docker image.

**Comment by ianw** [comment]
It looks like Python 3.8 support was added with https://github.com/theacodes/cmarkgfm-wheels/commit/ddcda9c6a7910e193e4aefa40bedcdb72477ecc2 however that build then appeared to fail in appveyor at the python2.7 stage https://ci.appveyor.com/project/theacodes/cmarkgfm-wheels/builds/30450845 which prevented any further builds

**Comment by mbarkhau** [comment]
With the release of `0.5.0` it appears the wheel files were only published for cp27.

I would advocate to yank the `0.5.0` release on pypi and future only publish `0.5.0a0`, `0.5.0a1`, `0.5.0a2`, etc. until the build of the wheels is working everywhere. This way there's no stress and downstream with users of `readme_renderer[md]` and `twine check`

**Comment by theacodes** [comment]
I ran out of time to fight the wheel publishing automation.

I won't be yanking the release.

**Comment by mbarkhau** [comment]
I understand you have limited time to debug build issues, I'm trying to advocate a minimum effort way for you to move forward without breaking downstream projects.

If you don't want to yank `0.5.0`, then I hope you will use the [pre-release](https://www.python.org/dev/peps/pep-0440/#pre-releases) mechanism in future, rather than just pray the build will work. Alternatively, the build should only publish to pypi if all build artifacts are created successfully.

**Comment by theacodes** [comment]
If someone else has the time to make that happen, great. Otherwise it will
remain as is.

**Comment by mbarkhau** [comment]
What do you think about switching to github actions?

**Comment by theacodes** [comment]
I'm indifferent. I just don't have time.
