### ISSUE TITLE
0.4.2 behavior not lining up with documentation

### ISSUE THREAD

**Issue by ColdHeat** [theacodes/cmarkgfm#25]
Is it just me or does the behavior outlined in the README of `CMARK_OPT_UNSAFE` not apply to the current latest in PyPI (0.4.2)? Pretty odd because the README says  >= 0.4.0 for the new behavior. 

Is this library still maintained and will there be a new release for it?

**Comment by theacodes** [comment]
Yeah it's still maintained but I have less time to devote to it. I'll try
to cut a release soon, but I am moving. Feel free to ping me again in 2
weeks if I haven't gotten around to it.

**Comment by ColdHeat** [comment]
Courtesy ping :) A new release would be great to line up with documentation!

**Comment by ColdHeat** [comment]
Hi there, any chance a new release could be cut?

**Comment by theacodes** [comment]
Hi, I'm in the middle of moving across the country and coordinating the
multi-wheel release takes a lot of attention. I'll try to do this as soon
as I can.

**Comment by ColdHeat** [comment]
Hi there, hope your move went well. Any chance on a new release?

**Comment by theacodes** [comment]
I'll try to cut a new release this week.

**Comment by theacodes** [comment]
Releasing now. Might take a while.
