### ISSUE TITLE
CI Recommendations [meta]

### ISSUE THREAD

**Issue by Andrew-Chen-Wang** [theacodes/cmarkgfm#32]
Just two recommendations:

- Use GitHub actions for your Windows CI rather than AppVeyor.
- Use GitHub actions to auto publish a patch release for a new cmark-gfm version?

Just thoughts. Great library!

**Comment by mbarkhau** [comment]
Hi Andrew,

- There is already a GitHub action that runs the Windows CI. I'm not sure it covers everything that the AppVeyor setup does, so I left that enabled.
- The latest release was published via a GitHub action and was built with cmark-gfm 0.29.0.gfm.0, which to my knowledge is the latest version.

Cheers.

**Comment by mbarkhau** [comment]
Looks like the issue was that the existing GH actions did not run for pull_request synchronize events. The issue should be fixed with PR #33.
