### ISSUE TITLE
Exposing tree iteration and node accessors

### ISSUE THREAD

**Issue by wagnerflo** [theacodes/cmarkgfm#34]
Hey there,

I've already asked this at your sister-project (https://github.com/Zopieux/pycmarkgfm/issues/2) but would like to repeat my question here so I can have clarification how to move forward.

While searching for a way to turn Markdown/Commonmark/GFM into a JSON representation (something like mdast preferably) I came across your library/ies. To be able to accomplish this I'd need access to the [tree iteration](https://man.archlinux.org/man/cmark-gfm.3.en#Iterator) functions (`cmark_iter_*`) as well as the [node accessors](https://man.archlinux.org/man/cmark-gfm.3.en#Accessors) (like `cmark_node_get_literal`, `cmark_node_get_heading_level` and so on).

The first part is already available in [pycmarkgfm/cmark.cffi.h#L50ff](https://github.com/Zopieux/pycmarkgfm/blob/553613c9abbebf4afd5b343191a9f1171428c9a2/pycmarkgfm/cmark.cffi.h#L50) the rest seems equally easy to do.

Before putting in the work to implement this would you accept a pull request with these changes? If yes should I include my mdast output function? And since I'm looking for a stable, maintained dependency for my project here: Are you planing to continue working on this library? (I can see myself helping a bit with that here and there.)

**Comment by mbarkhau** [comment]
Hi @wagnerflo, I'll have time try and understand the question later this week. Just wanted to give you a heads up.

**Comment by wagnerflo** [comment]
For clarification what I want to do. Turn Markdown like this

```markdown
# Heading

Some *em* text.
```

into something like this

```json
{
  "type": "root",
  "children": [
    {
      "type": "heading",
      "depth": 1,
      "children": [ { "type": "text", "value": "Heading" } ]
    },
    {
      "type": "paragraph",
      "children": [
        { "type": "text", "value": "Some " },
        { "type": "emphasis", "children": [ { "type": "text", "value": "em" } ] },
        { "type": "text", "value": " text." }
      ]
    }
  ]
}
```

**Comment by wagnerflo** [comment]
The cmark tree iterator, node accessors and a small Python loop with a stack and switch on node type should make this trivial to write. That's why I propose to expose these functions.

I'll do all the work including writing tests and prepare a nice pull request if you're interested in including this.

**Comment by mbarkhau** [comment]
Do I understand correctly, you would in principle be implementing something like this:

```python
import json
import cmarkgfm

tree = cmarkgfm.markdown_to_tree(markdown_text)
json_text = json.dumps(tree)
```

If so, then yes, I would regard this as within the scope of this project and would happily accept your PR.

**Comment by mbarkhau** [comment]
This was not a suggestion for an API btw. feel free to make those choices as you see appropriate.

**Comment by wagnerflo** [comment]
I'd be probably be calling it `markdown_to_mdast` since using an established [specification](https://github.com/syntax-tree/mdast) of how to represent the Markdown AST seems like a good idea, but yes that's it!

On Thurday I'll have a bit of time on a train. If I manage to find a quiet spot I'll start working on this then.

**Comment by wagnerflo** [comment]
Sorry for not updating. I found a bit of time on the train but not nearly enough to get this done. As this feature is a dependency of a project at work I promise I'll eventually get around to it. There's just a few more pressing things taking up my time currently.

**Comment by mbarkhau** [comment]
Dude, chill 🧘‍♂️

No need to stress, no need for promises, please take care.

**Comment by wagnerflo** [comment]
I'm sorry to say I will not be working on this. I'm leaving the employer that would have sponsored this work and personally currently have no use for it.
