### ISSUE TITLE
codeblocks: <pre lang=""> vs <pre><code class="">

### ISSUE THREAD

**Issue by nschloe** [theacodes/cmarkgfm#37]
On GitHub, the HTML preserves the language attribute (if given)
```html
<pre lang="python">
...
</pre>
```
This is somehow not properly reflected in cmarkgfm:
````python
import cmarkgfm

html = cmarkgfm.github_flavored_markdown_to_html("""
```python
a + 1
```""")

print(html)
````
```html
<pre><code class="language-python">a + 1
</code></pre>
```
Any idea what might cause this discrepancy?

**Comment by mbarkhau** [comment]
Can you investigate if this is related to the options? 

https://github.com/theacodes/cmarkgfm/blob/master/src/cmarkgfm/cmark.py#L10

**Comment by nschloe** [comment]
How do I set those options?

**Comment by mbarkhau** [comment]
~~~python
import cmarkgfm
from cmarkgfm.cmark import Options as cmarkgfmOptions

markdown_text = """
```python
a + 1
```"""

html = cmarkgfm.markdown_to_html(markdown_text)
print(repr(html))

html = cmarkgfm.markdown_to_html(markdown_text, options=cmarkgfmOptions.CMARK_OPT_GITHUB_PRE_LANG)
print(repr(html))
~~~

~~~shell
$ python scratch.py
'<pre><code class="language-python">a + 1\n</code></pre>\n'
'<pre lang="python"><code>a + 1\n</code></pre>\n'
~~~

Is this option not what you were looking for? Perhaps the pypa warehouse should set that option?

**Comment by nschloe** [comment]
> Perhaps the pypa warehouse should set that option?

Yes, looks like it. Can you explain why this option is not set by default in `github_flavored_markdown_to_html`?

**Comment by mbarkhau** [comment]
I cannot. If I had to guess, I would say it was simply an oversight. Perhaps the original author was focused on the extensions, and missed to set some default options, perhaps there was a change in how github renders the code blocks.

I would like to note that this test exists: 

~~~python
def test_github_flavored_markdown_to_html_pre_tag():
    text = u"```python\nprint('hello')\n```"
    result = cmark.github_flavored_markdown_to_html(text)
    expected = """
        <pre><code class="language-python">print('hello')
        </code></pre>
    """
    assert _normalize_ws(result) == _normalize_ws(expected)
~~~

Since this is apparently different than what GFM actually outputs these days (whether it changed or not), I would accept a PR which is based on the current behaviour. This would also be a good opportunity to find any other discrepancies that might exist.

**Comment by mbarkhau** [comment]
`git submodule update --init --recursive` ?

**Comment by nschloe** [comment]
Got it, thanks. I'm still confused by how the options are set though. In a Python world, setting the default option would go like
```python
def github_flavored_markdown_to_html(text, github_pre_lang=True/False):
```
With the current code, there is only one `options` argument, and it's an `int`? Going like
```python
def github_flavored_markdown_to_html(text, options=Options.CMARK_OPT_GITHUB_PRE_LANG):
```
works, _but only if the user doesn't set any other option._ I understand that this probably comes from ye olde times where binary strings `01001` where interpreted as `int`s. The question is if this is suitable for a Python interface. In any case, any hint on how to fix this?

**Comment by mbarkhau** [comment]
It's a bitmask, you set them with the binary or `|` operator:

```python
github_flavored_markdown_to_html(text, options=Options.CMARK_OPT_GITHUB_PRE_LANG | Options.CMARK_OPT_UNSAFE):
```

**Comment by nschloe** [comment]
Right. How to set a default value though without having it override if a user wants to set a different option?

**Comment by mbarkhau** [comment]
Sentinel pattern.

```python
def github_flavored_markdown_to_html(text, options=None):
    if options is None:
        options = Options.CMARK_OPT_GITHUB_PRE_LANG | ...
```

**Comment by nschloe** [comment]
If `options` is `None`, all is fine. It's clear that the user wants all default values.

If the user sets some other value, e.g., `CMARK_OPT_UNSAFE` what do we do? We don't know if the user intentionally didn't set `CMARK_OPT_GITHUB_PRE_LANG` or if she doesn't care and just wants to go with the default.

**Comment by mbarkhau** [comment]
Right. I think as a user, I would want to consider options to be additional options. If I call the function, I want gfm AND also some other option. If I don't want gfm, I'd use the other function.

In other words, forget the sentinel pattern and just apply the defaults as a bitmask

```python
def github_flavored_markdown_to_html(text, options=0):
    options = (
        Options.CMARK_OPT_GITHUB_PRE_LANG
        | Options.CMARK_OPT_...
```

This is my thinking at least.

**Comment by nschloe** [comment]
I'll do that for now. The better pattern would probably be to use python-style options
```python
def github_flavored_markdown_to_html(text, github_pre_lang=True, hardbreaks=False, validate_utf8=False, ...)
```
and translate them into a bitmask for cmark.

**Comment by mbarkhau** [comment]
Thanks for the PR @nschloe.

Conceptually speaking, this is a breaking change (though at least the API didn't change), so I'll be making a MINOR release.
Before I do that (later this week), are you interested in investigating the broader issue of making sure the output of this function aligns with GFM? This may be only one instance of a few discrepancies.

**Comment by nschloe** [comment]
> are you interested in investigating the broader issue of making sure the output of this function aligns with GFM?

Interested yes, but right now I don't have the capacity for it. I will report differences when I find them though.

**Comment by mbarkhau** [comment]
As a final thing for the PR. Can you update the docstring. I think the "just applies..." portion is no longer correct.

**Comment by nschloe** [comment]
What would like to read it?

**Comment by mbarkhau** [comment]
Hah, I guess I'll think of something later. Ok, merging.
