### ISSUE TITLE
Verify GFM Conformity

### ISSUE THREAD

**Issue by mbarkhau** [theacodes/cmarkgfm#39]
#37 showed that there was at least one discrepancy between the output of `github_flavored_markdown_to_html` and what GFM actually produced. This issue is a reminder find any other differences.

**Comment by mbarkhau** [comment]
I'm reading through the [examples in the spec](https://github.github.com/gfm/#example-112) and it appears to me that the original behavior (without `CMARK_OPT_GITHUB_PRE_LANG`) is what the spec says. I wonder if the spec is out of sync with what github uses.

For `cmark-gfm` to do this, you must explicitly specify `--github-pre-lang` and I'm not sure in what context this is done or appropriate.

I am currently inclined to revert #38 

@nschloe @di any comment?

**Comment by nschloe** [comment]
> I wonder if the spec is out of sync with what github uses.

I mean, you can just have a look, right? I haven't seem `class="language-x"` anywhere on GitHub for while now.

**Comment by mbarkhau** [comment]
If I look at what github is rendering, it doesn't look like anything from cmark-gfm. 

````
<div class="highlight highlight-source-python position-relative"><pre>
````

**Comment by nschloe** [comment]
That's right. It doesn't do that for all languages though; try "```abcxyz" or so.

**Comment by mbarkhau** [comment]
@nschloe it appears you are correct.

@di, as you are the main downstream user of this package, I'd appreciate your feedback. I've seen that your pin is to [`cmarkgfm>=0.5.0,<0.6.0`](https://github.com/pypa/readme_renderer/blob/main/setup.py#L62), so my current plan is to release `0.6.0` with this change.
