### ISSUE TITLE
New Release

### ISSUE THREAD

**Issue by ColdHeat** [theacodes/cmarkgfm#44]
Hi all, in light of #43 is it possible to get a new release on PyPI?

**Comment by theacodes** [comment]
Yes, I just have not yet had time.

**Comment by theacodes** [comment]
The new release has been made. It will take a little while longer for wheels to appear to on PyPI. https://github.com/theacodes/cmarkgfm/releases/tag/2022.3.4

**Comment by ColdHeat** [comment]
Thanks! FYI your setup.py is 0.8.0 so calver didn't take on PyPI. Not sure if that's intended or not.

**Comment by theacodes** [comment]
Yeah I know. I am only human. Bleep bloop.
