### ISSUE TITLE
Where is the rendered `.html` output file located?

### ISSUE THREAD

**Issue by yasirroni** [theacodes/cmarkgfm#47]
Using

```python
import cmarkgfm

current_path = os.path.abspath(os.path.dirname(__file__))
with open(os.path.join(current_path, 'FILE.md'), 'r') as f:
    text = f.readlines()
html = cmarkgfm.github_flavored_markdown_to_html(''.join(text))
```

produce nothing.

Adding

```python
with open(os.path.join(current_path, 'FILE.html'), 'a') as f:
    f.write(html)
```

 Create plain html format

**Comment by mbarkhau** [comment]
The function you are using has as its input a `str` and returns as its output a `str`.

```
In [3]: cmarkgfm.github_flavored_markdown_to_html("# Hello\nworld")
Out[3]: '<h1>Hello</h1>\n<p>world</p>\n'
```

Your question appears to be a more general question about python file handling or paths and I think you will have to debug this on your own. At least I don't see how I can help you with that from here. As a tip, I think you may find [this tutorial on the `pathlib` module to be helpful](https://realpython.com/python-pathlib/).

Best of luck.

**Comment by yasirroni** [comment]
Nope, the problem is not in Python paths, but on the non existence of `.css` to create the GitHub flavored markdown.

It seems that this package did not support that part?

**Comment by mbarkhau** [comment]
Correct, you must supply the css yourself. You must also supply any surrounding markup yourself.

```python
TEMPLATE = """
<html lang="en">
<head>
<title>My Page</title>
<link rel="stylesheet" href="style.css">
</head>
<body>{html_content}</body>
</html>
"""

html_content = cmarkgfm.github_flavored_markdown_to_html(text)
html = TEMPLATE.format(html_content=html_content)
```

**Comment by yasirroni** [comment]
Feature request: warp all that for user. :)

You can look other implementation on github.css in [markdown-viewer](https://github.com/simov/markdown-viewer/blob/master/themes/github.css) that come with MIT License.

**Comment by mbarkhau** [comment]
Out of scope. Best of luck.
