### ISSUE TITLE
CVE issues have been fixed?

### ISSUE THREAD

**Issue by yuzibo** [theacodes/cmarkgfm#59]
Hi,

I noticed that there are some CVE issue from Debian pages:
https://security-tracker.debian.org/tracker/source-package/python-cmarkgfm

I just want to confirm these CVE issue have been fixed in new release? If so I can import the new release 
and close these bug on Debian.

Thanks.

**Comment by mbarkhau** [comment]
This is the first I've heard of this and I'm not aware of any work on it.

On a first glance, I can't determine what the issue even is about and what might need to be fixed.

**Comment by yuzibo** [comment]
I got confused here also. 
The explanation I can make here is the tracker is false positive maybe due to similar project name？
The is reportbug for [cmark-gfm] https://bugs.debian.org/cgi-bin/bugreport.cgi?bug=1020588.
Really odd: https://tracker.debian.org/pkg/python-cmarkgfm
I have to confirm it for Debian security team in one more day.

**Comment by theacodes** [comment]
These seem to all be related to the wrapped C library, `cmark-gfm`. I'd reach out upstream and to the Debian maintainer if you're worried about CVEs for this.
