### ISSUE TITLE
Python 3.12 Wheels

### ISSUE THREAD

**Issue by Hoolean** [theacodes/cmarkgfm#64]
Hello!

In the spirit of #55, I am making an issue to track the generation of wheels for Python 3.12 too : )

**Comment by theacodes** [comment]
Rad. Thanks!

**Comment by QuLogic** [comment]
Just checking, but it doesn't seem like the 3.12 wheels were uploaded for the recent release?

**Comment by theacodes** [comment]
Ah, it seems I need to kick the CI a little more to get it all to work. I can confirm that Python 3.12 wheels are up at https://pypi.org/project/cmarkgfm/#files
