### ISSUE TITLE
readme should list dependencies for install

### ISSUE THREAD

**Issue by alanbork** [theacodes/cmarkgfm#66]
eg for windows :

 Microsoft Visual C++ 14.0 or greater is required. Get it with "Microsoft C++ Build Tools": https://visualstudio.microsoft.com/visual-cpp-build-tools/

as a python developer that's a pretty big dependency to install just for this tool.

**Comment by theacodes** [comment]
Most of the time there should be a pre-built wheel for you. Sometimes we need to poke the bot to build them.

**Comment by alanbork** [comment]
That is sort of what I expected from the readme, to be honest.

**Comment by theacodes** [comment]
We just published wheel for 3.12 on all common platforms, I'm closing this for now.
