### ISSUE TITLE
New release to build Python 3.13 wheel

### ISSUE THREAD

**Issue by elisalle** [theacodes/cmarkgfm#70]
The current cmarkgfm release on PyPI (2024.1.14) only supports wheels for Python 3.12 and older.
For a Docker build of ours which relies indirectly on cmarkgfm, we'd like to use Python 3.13 now it's the stable release, without installing build-essentials etc to build packages. I see that the master branch of cmarkgfm does already support building wheels for Python 3.13; would it be possible to create a new release on PyPI?

**Comment by theacodes** [comment]
Done, https://github.com/theacodes/cmarkgfm/releases/tag/2024.11.20. It may take a while for the wheels to get uploaded.
